CheckerNetwork/zinnia

- .prettierignore
- .prettierrc.yaml
- docs/architecture-decision-records/2023-01-initial-architecture.md
- docs/architecture-decision-records/template.md
- docs/architecture-decision-records: add template
- ADR: initial architecture for the Station Runtime
> ADR: initial design

- Cargo.lock
- cli/Cargo.toml
- cli/args.rs
- cli/main.rs
- cli/tests/cli_tests.rs
- cli: test parsing of CLI args
- cli: integration tests spawning CLI executable
See #5
> Automated tests (unit + integration)

- .cargo/config.toml
- .github/workflows/ci.yaml
- Cargo.toml
- cli/Cargo.toml
- cli/runtime.rs
- cli/tests/cli_tests.rs
Copy'n'paste from rust-libp2p:
https://github.com/libp2p/rust-libp2p/blob/3c120322a9f/.github/workflows/ci.yml
> ci: setup GitHub Actions workflow

- .github/dependabot.yaml
- .github/workflows/cargo-audit.yml
- .github/workflows/ci.yaml
- ci: periodically run cargo-audit
- ci: configure Dependabot
> ci: setup cargo-audit and Dependabot

- README.md
- cli/README.md
- docs/building-modules.md
> docs: initial docs for module builders

- .github/workflows/ci.yaml
- .prettierignore
- .prettierrc.yaml
> ci: run `prettier --check .`

- .editorconfig
- .rustfmt.toml
- Cargo.toml
- README.md
- cli/README.md
- cli/args.rs
- cli/main.rs
- cli/tests/cli_tests.rs
- docs/architecture-decision-records/2023-01-initial-architecture.md
- docs/architecture-decision-records/2023-01-switching-to-deno-core.md
- docs/building-modules.md
- docs/release.md
- ext/libp2p/README.md
- ext/libp2p/js/01_peer.js
- ext/libp2p/lib.rs
- ext/libp2p/peer.rs
- ext/libp2p/peer/behaviour.rs
- ext/libp2p/peer/handler.rs
- ext/libp2p/peer/protocol.rs
- runtime/README.md
- runtime/js/06_util.js
- runtime/js/98_global_scope.js
- runtime/js/99_main.js
- runtime/runtime.rs
- runtime/tests/js/fetch_tests.js
- runtime/tests/js/globals_tests.js
- runtime/tests/js/libp2p_tests.js
- runtime/tests/runtime_integration_tests.rs
- runtime/vendor.js
Change Rust setup to use the default formatting style:
- Increate max line width to 100 characters
- Use 4 spaces for indentation
Update Prettier config for JavaScript and Markdown for consistency:
- Increate max line width to 100 characters
Reformat all files using the new rules.
> chore: max width 100, rust ident 4 chars

- .github/workflows/ci.yaml
- .github/workflows/release.yml
> feat: support Apple Silicon (M1/M2)

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/main.rs
- ext/libp2p/Cargo.toml
- ext/libp2p/peer.rs
- runtime/Cargo.toml
- deps: sort Cargo.toml entries
- feat: logger configurable via env vars
> feat: logger configurable via env vars

- docs/building-modules.md
- runtime/js/98_global_scope.js
- runtime/runtime.rs
- runtime/tests/js/libp2p_tests.js
- runtime/tests/js/webcrypto_tests.js
- runtime/tests/runtime_integration_tests.rs
> feat: Web Cryptography APIs

- .github/workflows/ci.yaml
> ci: run on Windows

- .cargo/config.toml
- .github/workflows/release.yml
- Cargo.toml
> feat: build release binaries for Windows

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
Changelog:
https://github.com/denoland/deno/releases/tag/v1.32.1
> feat: upgrade Deno to 2023.03.23

- Cargo.lock
- ext/libp2p/Cargo.toml
- ext/libp2p/peer.rs
- ext/libp2p/peer/behaviour.rs
Changelogs:
- v0.51.2: https://github.com/libp2p/rust-libp2p/blob/libp2p-v0.51.2/CHANGELOG.md
- v0.51.3: https://github.com/libp2p/rust-libp2p/blob/libp2p-v0.51.3/CHANGELOG.md
> deps: upgrade libp2p from v0.51.1 to v0.51.3

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
- runtime/runtime.rs
Changelogs:
- https://github.com/denoland/deno/releases/tag/v1.32.4
- https://github.com/denoland/deno/releases/tag/v1.32.3
- https://github.com/denoland/deno/releases/tag/v1.32.2
> feat: upgrade Deno to 2023.04.12

- cli/README.md
- daemon/README.md
- docs: add README for `zinniad`
- docs: add zinnia-linux-arm64 to the download table
Resolves #75
> docs: add README for `zinniad`

- runtime/runtime.rs
When loading modules from filesystem, resolve symlinks in the module path before checking whether the target file is inside the module root directory (the sandbox).
This is a follow-up for #205, see also #43.
> fix: resolve symlinks before checking module paths

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- daemon/Cargo.toml
- daemon/main.rs
- daemon/tests/daemon_tests.rs
- daemon/tests/fixtures/fetch-ipfs-with-delay.js
> fix: delete Lassie temp when zinniad starts

- cli/main.rs
- daemon/main.rs
- runtime/runtime.rs
- runtime/tests/helpers/mod.rs
- refactor: shared Lassie config
- fix: change Lassie timeouts to 1 day
Resolves #274
> fix: change Lassie timeouts to 1 day

- docs/building-modules.md
> docs: explain IPFS retrieval timeouts

- docs/building-modules.md
- runtime/js/vendored/asserts.bundle.js
- runtime/vendor.js
Bring in new `assert` features, e.g. https://github.com/denoland/deno_std/pull/3496 and https://github.com/denoland/deno_std/pull/3577
> deps: upgrade deno_std to v0.201.0

- docs/building-modules.md
> fix: Update building-modules.md

- docs/building-modules.md
- runtime/js/vendored/asserts.bundle.js
- runtime/vendor.js
Release notes:
- https://github.com/denoland/deno_std/releases/tag/0.208.0
- https://github.com/denoland/deno_std/releases/tag/0.209.0
- https://github.com/denoland/deno_std/releases/tag/0.210.0
- https://github.com/denoland/deno_std/releases/tag/0.211.0
- https://github.com/denoland/deno_std/releases/tag/0.212.0
- https://github.com/denoland/deno_std/releases/tag/0.213.0
- https://github.com/denoland/deno_std/releases/tag/0.214.0
> feat: upgrade deno_std to v0.214.0

- docs/building-modules.md
- runtime/js/vendored/asserts.bundle.js
- runtime/vendor.js
The package has been moved to https://jsr.io/@std/assert
> deps: upgrade Deno assert from v0.214.0 to v0.226.0

- .github/workflows/ci.yaml
- daemon/tests/daemon_tests.rs
- ext/libp2p/peer.rs
- ext/libp2p/peer/behaviour.rs
- runtime/tests/js/ipfs_retrieval_tests.js
- **test: retrieve the CID hosted by our Frisbii**
- **fix: remove unused struct field**
- **ci: bump Rust to v1.85**
Close https://github.com/CheckerNetwork/zinnia/issues/676
> ci: upgrade Rust to v1.85 + maintenance

- .github/workflows/ci.yaml
Prevent regressions like https://github.com/CheckerNetwork/zinnia/issues/689 from happening again.
> ci: test release builds for all changes

- .github/dependabot.yaml
Ref:
- https://github.com/CheckerNetwork/zinnia/pull/696
- https://github.com/CheckerNetwork/zinnia/issues/676
> deps: configure Dependabot to ignore Deno updates

- runtime/tests/js/webapis_tests.js
See https://github.com/CheckerNetwork/zinnia/pull/735#pullrequestreview-2773669122
Parent issue:
- https://github.com/CheckerNetwork/zinnia/issues/676
> test: explanatory comments for import.meta.* tests
