docs/building-modules.md
It turns out we support all standard JS APIs, including things like `Date` and `Intl`.
Example code:
```js
console.log('NOW:', Date.now());
console.log('new Date:', new Date());
console.log(encodeURI('hello world'))
const regionNamesInEnglish = new Intl.DisplayNames(['en'], { type: 'region' });
const regionNamesInTraditionalChinese = new Intl.DisplayNames(['zh-Hant'], { type: 'region' });
console.log(regionNamesInEnglish.of('US'));
console.log(regionNamesInTraditionalChinese.of('US'));
```
Example output:
```
❯ zinnia run jsapis.js
NOW: 1675861800870
new Date: 2023-02-08T13:10:00.870Z
hello%20world
United States
美國
```
=> docs: standard JavaScript APIs

.github/workflows/ci.yaml
I hope this change will speed up CI builds.
=> ci: cache Rust build artifacts on Linux too

.github/workflows/ci.yaml, Cargo.toml, cli/Cargo.toml, runtime/Cargo.toml
Remove Minimal Supported Rust Version from our `Cargo.toml` files and remove the CI build steps checking the conformance.
At this early stage of the project, we don't need to support older versions of Rust. Having faster CI builds is more important to allow us to iterate faster.
=> feat!: remove Minimal Supported Rust Version

.prettierrc.yaml, Cargo.lock, Cargo.toml, cli/Cargo.toml, docs/building-modules.md, runtime/Cargo.toml, runtime/js/06_util.js, runtime/js/98_global_scope.js, runtime/js/99_main.js, runtime/lib.rs, runtime/runtime.rs, runtime/tests/integration/globals_tests.rs, runtime/tests/integration/mod.rs, runtime/tests/integration/timers_tests.rs, runtime/tests/runtime_integration_tests.rs
Add JS APIs from `deno_web` crate.
Most notably:
- Events and `AbortController`
- `TextEncoder` and `TextDecoder` (will be needed for WASM)
- `File`, `FileReader` and `Blob`
- `MessageChannel`, `structuredClone` and friends
- `atob` and `atoa` (will be needed for WASM)
- `setTimeout`, `setInterval`, and friends
- `Performance` APIs
- Streams (`ReadableStream`, `WritableStream`, etc.)
- `URL` and friends
See #7
=> feat: add `deno_web` APIs like `setTimeout`

.github/workflows/ci.yaml
Our project is very heavy on dependencies, it takes ~10 minutes to fetch and build them all. To keep our CI builds fast, we need to cache as much as we can.
In this pull request, I am reworking the CI structure so that we always start with building the project for the given platform, and then fetching the artefacts produced by that build to speed up all subsequent steps like testng and linting
=> ci: improve caching of dependencies

.github/workflows/ci.yaml
- ci: add `--target` to `cargo test`
- ci: build all targets (bins, libs, tests, etc.)
=> ci: improve caching of build artifacts

runtime/runtime.rs, runtime/tests/js/webapis_tests.js, runtime/tests/runtime_integration_tests.rs, runtime/vendor.js, runtime/vendored/asserts.bundle.js
**feat: vendor `asserts` from Deno stdlib**
- Allow module authors to import from https://deno.land/std@0.177.0/testing/asserts.ts
- This is a short-term hack until we implement #43 
**test: add smoke tests for Web APIs**
This is a follow-up to improve test coverage of the APIs we are exposing from `deno_web` crate, see
- #34 
- #40
Resolves #7
=> feat: assertion library + smoke tests for Web APIs

.github/workflows/ci.yaml
When testing crates independently, we are not able to build `zinnia_libp2p`
(see #48):
```
Compiling v8 v0.60.1
error: could not find native static library `rusty_v8`, perhaps an -L flag is missing?
error: could not compile `v8` due to previous error
```
In this change, I am reworking the test matrix to test all crates together. Cargo is already doing a great job in running tests in parallel.
It takes longer to build our tests than to execute them, so this change may speed up our CI builds too.
=> ci: test all crates together

docs/building-modules.md
The response stream is async-iterable, we need to use `for async`.
=> docs: fix libp2p example code

docs/release.md
Update release instructions and add `--tag-prefix ""` argument to `cargo release`. This way we create a single tag shared by all crates (e.g. `v0.1.0`) instead of per-crate tags like `zinnia-v0.1.0`.
=> docs: create single tag when releasing

Cargo.lock, ext/libp2p/Cargo.toml
Some older go-libp2p nodes are still using RSA public keys. This PR enables
Zinnia to connect to such nodes too.
=> feat: support libp2p RSA public keys

.github/workflows/cargo-audit.yml, .github/workflows/ci.yaml
- ci: remove deprecated `actions-rs/audit-check`
- ci: remove deprecated `actions-rs/cargo`
Close #68, see also
- #73
=> ci: remove deprecated 3rd-party GH actions

ext/libp2p/peer.rs
Use "v1 lazy" variant of multistream-select.
> A "lazy" variant is identical on the wire but whereby the dialer
> delays flushing protocol negotiation data in order to combine it
> with initial application data, thus performing 0-RTT negotiation.
Based on the discussion in https://github.com/filecoin-station/zinnia/pull/48#discussion_r1117196369
=> feat: allow 0-RTT protocol negotiation

Cargo.lock, cli/main.rs, ext/libp2p/Cargo.toml, ext/libp2p/lib.rs, ext/libp2p/peer.rs, ext/libp2p/peer/config.rs, ext/libp2p/peer/protocol.rs, runtime/runtime.rs, runtime/tests/runtime_integration_tests.rs
Enable handling of `Ping` and `Identify` requests by all Zinnia nodes.
This fixes compatibility with the rust-libp2p implementation of Ping protocol, which we need to allow us to test our request-response-like behavior against a Ping protocol implementation.
This is a follow-up for
- #83 
- #84
and a part of
- #73
=> feat: fix compat with Rust, enable Ping + Identify

.github/workflows/release.yml, Cargo.toml
- Before this change, we were attaching the uploaded binaries to the workflow run. This PR changes the workflow to attach the binaries to a GH Release.
- Disable LTO on Windows in an attempt to fix the failing release build
- Rename release binaries
- Disable incremental release builds
See #23
=> ci: upload release binaries to GH Release

README.md, docs/building-modules.md, examples/ping-probe/README.md, examples/ping-probe/probe.js
=> docs: add an example module - ping-probe

.github/workflows/ci.yaml
Before this change, we had two matrix items with the same triple `x86_64-apple-darwin`.
This commit changes one of those items to use `aarch64-apple-darwin` instead.
=> ci: fix Apple arm64 setup

.github/workflows/ci.yaml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, ext/libp2p/js/01_peer.js, ext/libp2p/lib.rs, runtime/Cargo.toml, runtime/js/06_util.js, runtime/js/98_global_scope.js, runtime/js/99_main.js, runtime/runtime.rs
Upgrade Deno crates:
- `deno_core` from `0.171.0` to `0.173.0`
- `deno_runtime` from `0.97.0` to `0.99.0`
Rework our internal modules to use the new ES module style (see https://github.com/denoland/deno/pull/17648 and and https://github.com/denoland/deno/pull/17683)
**The changes are best reviewed with whitespace-changes ignored.**
Rework the way how we call async ops - see https://github.com/denoland/deno/pull/17899
Disable Windows support for the time being because GitHub Action Windows runners don't have enough disk space for building Zinnia 😱 I opened #99 to investigate and fix this problem.
See #73
=> feat: upgrade Deno core and extensions

docs/release.md
Update the docs to describe the new process based on a draft release created by our Release CI/CD workflow.
=> docs: update release process

runtime/runtime.rs
See https://v8.dev/docs/untrusted-code-mitigations#consider-tuning-your-offered-high-precision-timers
> A high-precision timer makes it easier to observe side channels in the SSCA
> vulnerability. If your product offers high-precision timers that can be
> accessed by untrusted JavaScript or WebAssembly code, consider making these
> timers more coarse or adding jitter to them.
Connect to #73
=> docs: explain why hrtime is disabled

Cargo.lock, runtime/Cargo.toml, runtime/lib.rs, runtime/runtime.rs, runtime/vendored.rs, runtime/vendored/colors.rs, runtime/vendored/fmt_errors.rs
Rework our code to depend on individual Deno extension crates directly, so that there are less dependencies to download and build.
I was hoping to get a smaller binary size, but the Rust compiler and linker are too good in removing unused code. This change shaves only about 15KB from 54.6MB.
I also had to vendor `colors` and `fmt_errors` from `deno_runtime`, as they are not offered by other crates. I opened a GH issue in Deno (https://github.com/denoland/deno/issues/18179) to discuss moving these two files somewhere else.
=> refactor: replace deno_runtime with ext crates

Cargo.lock, Cargo.toml, cli/main.rs, runtime/Cargo.toml, runtime/lib.rs, runtime/tests/runtime_integration_tests.rs
```
deno_core: 0.175.0
deno_console: 0.93.0
deno_crypto: 0.106.0
deno_crypto: 0.107.0
deno_fetch: 0.117.0
deno_url: 0.93.0
deno_web: 0.124.0
deno_webidl: 0.93.0
```
Release notes:
https://github.com/denoland/deno/releases/tag/v1.31.3
Notable changes:
"Upgrades bytes crate from =1.2.1 to ^1.4.0" (https://github.com/denoland/deno/pull/18123) removes another dependency version conflict preventing us from upgrading libp2p to a newer version
=> feat: upgrade Deno to 2023.03.16

Cargo.lock, ext/libp2p/Cargo.toml, ext/libp2p/lib.rs, ext/libp2p/peer.rs, ext/libp2p/peer/behaviour.rs
See https://github.com/filecoin-station/zinnia/issues/73
- upgrade libp2p to 0.51.1 
- [0.51.0 release notes](https://github.com/libp2p/rust-libp2p/blob/v0.51.0/CHANGELOG.md#0510)
- accommodate changes related to libp2p-identity
- See https://github.com/libp2p/rust-libp2p/pull/3350  
- accommodate the removal of EitherError
- https://github.com/libp2p/rust-libp2p/pull/3337
- https://github.com/libp2p/rust-libp2p/issues/3622
- accommodate changes in NetworkBehaviour
- https://github.com/libp2p/rust-libp2p/pull/3254
- https://github.com/libp2p/rust-libp2p/pull/3328
@mxinden could you PTAL if my changes look sensible and if I didn't miss anything?
=> feat: upgrade libp2p to 0.51.1

Cargo.lock
Run `cargo update --aggressive` to update deep dependencies and fix
problems reported by `cargo audit`.
Connect to #73
=> deps: update deep dependencies

docs/building-modules.md, runtime/js/99_main.js, runtime/runtime.rs, runtime/tests/js/station_apis_tests.js, runtime/tests/runtime_integration_tests.rs
Allow modules to access the wallet address where to send rewards.  The value is hard-coded to a testnet address for now.
When running inside the Station, this API will return the Station wallet address.
In the future, we can allow CLI users to configure this address too.
Connect to #75
=> feat: add `Zinnia.walletAddress` API

Cargo.lock, Cargo.toml, ext/libp2p/lib.rs, runtime/Cargo.toml, runtime/runtime.rs
Relevant changes:
- [feat(core): deno\_core::extension! macro to simplify extension registration]( https://github.com/denoland/deno/pull/18210)
- [feat(ext/url): URLSearchParams.size](https://github.com/denoland/deno/pull/17884)
- [feat(serde\_v8): support BigInt serialization]( https://github.com/denoland/deno/pull/18225)
- fix(runtime): Extract error code for all OS error variants
- [perf(core) Reduce copying and cloning in extension initialization]( https://github.com/denoland/deno/pull/18252)
- [perf(core) Reduce script name and script code copies]( https://github.com/denoland/deno/pull/18298)
- perf(core): preserve ops between snapshots
- perf(core): use static specifier in ExtensionFileSource
- perf: disable WAL for transpiled source cache
- perf: disable runtime snapshot …
=> feat: upgrade Deno to 2023.03.22

Cargo.lock, Cargo.toml, daemon/Cargo.toml, daemon/args.rs, daemon/main.rs, daemon/station_reporter.rs, runtime/reporter.rs
Implement a new binary `zinniad` that can run multiple modules at the same time and acts as another Filecoin Station Module.
See #75 
- #142
- #143
- #144
- #145
- #146
- #147
- #148
```
❯ zinniad --help
Zinnia daemon runs Zinnia modules inside Filecoin Station.
Usage: zinniad [OPTIONS] --wallet-address <WALLET_ADDRESS> [FILES]...
Arguments:
[FILES]...  List of modules to run, where each module is a single JS file. We don't make any assumptions about the directory layout of modules. Paths are resolved relatively to the current working directory
Options:
-w, --wallet-address <WALLET_ADDRESS>
Address of Station's built-in wallet (required) [env: WALLET_ADDRESS=]
-r, --root-dir <ROOT_DIR>
Directory where to keep state files (optional). Defaults to a platform-specific location, e.g. …
```
=> feat: `zinniad` for Filecoin Station

.github/workflows/release.yml
Modify our Release workflow to create packages for `zinniad` binary too.
See #75
=> feat: build `zinniad` release binaries

.github/workflows/release.yml
This is a follow-up for #158 fixing an accidental omission.
See also #75
=> feat: sign `zinniad` binary for macOS

docs/architecture-decision-records/2023-03-filesystem-conventions.md, docs/architecture-decision-records/2023-03-integration-with-station.md
Remove `ROOT_DIR` configuration option and introduce two new configurable locations:
- `CACHE_ROOT` for storing temporary files. This directory must not be shared with other computers (e.g. via Windows roaming) and should be excluded from backups by the default OS convention.
- `STATE_ROOT` for storing persistent files. This directory must not be shared with other computers (e.g. via Windows roaming) and should be included in backups by default.
=> docs: `CACHE_ROOT` and `STATE_ROOT` [ADR]

.github/workflows/release.yml, build/entitlements.mac.plist
- Bump the minimal required macOS version to 10.9 (see [Apple Notarization Requirements](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution))
- Notarize `zinnia` and `zinniad`
See #23
=> feat: notarize macOS binaries

.github/workflows/ci.yaml
libp2p migrated from `prost` to `quick-protobuf`, this removed `protoc`
dependency. See https://github.com/libp2p/rust-libp2p/pull/3312
=> feat: remove `protoc` dependency

cli/README.md
Rework CLI Installation documentation to tell users where to download the release binaries of `zinnia` we are building for them.
We need to land #161 first.
See also #23
=> docs: install prebuilt binaries

daemon/args.rs
Replace `ROOT_DIR` with two more fine-grained locations.
I decided to remove short versions for these two new config options, as I feel `-s` and `-c` is too ambiguous. I don't need to set these two options while experimenting with `zinniad` thanks to their reasonable defaults, which is another argument for not having a short version.
_The diff is best viewed with whitespace-only changes ignored._
Closes #153
```
❯ zinniad --help
Zinnia daemon runs Zinnia modules inside Filecoin Station.
Usage: zinniad [OPTIONS] --wallet-address <WALLET_ADDRESS> [FILES]...
Arguments:
[FILES]...  List of modules to run, where each module is a single JS file. We don't make any assumptions about the directory layout of modules. Paths are resolved relatively to the current working directory
Options:
-w, …
```
=> feat: introduce `STATE_ROOT` and `CACHE_ROOT`

daemon/args.rs
- docs: descriptive value names for zinniad args
- fix!: rename zinniad env var to FIL_WALLET_ADDRESS
New help output:
```
Zinnia daemon runs Zinnia modules inside Filecoin Station.
Usage: zinniad [OPTIONS] --wallet-address <FIL ADDRESS> [FILES]...
Arguments:
[FILES]...  List of modules to run, where each module is a single JS file. We don't make any assumptions about the directory layout of modules. Paths are resolved relatively to the current working directory
Options:
-w, --wallet-address <FIL ADDRESS>
Address of Station's built-in Filecoin wallet (required) [env: FIL_WALLET_ADDRESS=]
--state-root <LOCAL STATE DIR PATH>
Directory where to keep state files [env: STATE_ROOT=] [default: "/Users/bajtos/Library/Application Support/app.filstation.zinniad"]
--cache-root <CACHE DIR PATH> …
```
=> fix!: rename zinniad env var to FIL_WALLET_ADDRESS

Cargo.lock, daemon/Cargo.toml, daemon/main.rs, daemon/state.rs, daemon/station_reporter.rs, runtime/console_reporter.rs
- zinniad: persist "jobs completed" across restarts
- refactor: code cleanup in reporters
Resolves #148
The implementation is a bit hacky. We will need to refactor it to enable support for more than one module (see #144). Right now, I am optimising to deliver Zinnia in Station ASAP.
It's probably best to review the changes commit by commit.
=> feat: persist job counter across restarts

.prettierignore, docs/building-modules.md, runtime/ext.rs, runtime/js/vendored/asserts.bundle.js, runtime/module_loader.rs, runtime/tests/js/fetch_tests.js, runtime/tests/js/libp2p_tests.js, runtime/tests/js/module_loader_tests.js, runtime/tests/js/station_apis_tests.js, runtime/tests/js/webapis_tests.js, runtime/tests/js/webcrypto_tests.js, runtime/vendor.js
Example usage:
```js
import { test } from "zinnia:test";
import { assertEquals } from "zinnia:assert";
test("AbortController", () => {
assertEquals(typeof AbortController, "function", "typeof AbortController");
assertEquals(AbortController.name, "AbortController", "AbortController.name");
});
```
See #44
=> feat: embed Deno assertions as `zinnia:assert`

cli/main.rs, daemon/main.rs, runtime/lib.rs, runtime/module_loader.rs, runtime/runtime.rs, runtime/tests/js/module_loader_tests.js, runtime/tests/runtime_integration_tests.rs
Relax the restriction preventing Zinnia modules to load files only under the directory of the main entry point. This enables developers to run individual test files regardless of where they are in the project tree, while allowing the test files to import files from anywhere in the project.
The changes are affecting `zinnia` CLI only. When running inside Filecoin Station, `zinniad` keeps enforcing the sandbox.
See #44
=> feat: `zinnia` CLI can import JS from anywhere

.github/workflows/release.yml
See 2917acbf1ea54717574905bffed259b6a770b8d6 (#165)
Resolves #219
=> ci: remove `protoc` dependency from release builds

Cargo.lock, daemon/main.rs, runtime/Cargo.toml, runtime/runtime.rs, runtime/tests/fetch_api_tests.rs
Change the value sent in `User-Agent` request headers to match the agent version used to identify our libp2p node.
Modify the agent string as follows:
- CLI keeps reporting `zinnia/0.9.0` (`0.9.0` is the current version)
- Zinniad (Filecoin Station) reports the user agent as a combination of the Zinnia version plus the name of the Station module running.
Example: `zinniad/0.9.0 dummy-module`
Resolves #76
=> fix: user agent reported by Fetch client

docs/building-modules.md
=> docs: testing guide for module authors

runtime/ext.rs, runtime/js/internals.js, runtime/js/test.js, runtime/tests/js/test_runner_tests/failing_tests.activity.txt, runtime/vendored.rs, runtime/vendored/cli_tools.rs
Vendor `format_test_error()` from Deno CLI and use it to format test failures.
Output before my changes - notice the stack frames pointing to Zinnia internals (`ext:zinnia_runtime`)
New output:
Output of `deno test` for comparison:
See #44
=> feat: prettify test failures

Cargo.lock, Cargo.toml, runtime/Cargo.toml, runtime/runtime.rs
Changelogs:
- https://github.com/denoland/deno/releases/tag/v1.34.0
- https://github.com/denoland/deno/releases/tag/v1.34.1
- https://github.com/denoland/deno/releases/tag/v1.34.2
=> feat: upgrade Deno to 2023.06.08

docs/building-modules.md
Also add a ToC entry to make it easier to find Station-related APIs.
The new structure:
=> docs: fix heading levels in building-modules

cli/main.rs, daemon/main.rs, docs/building-modules.md, runtime/js/90_zinnia_apis.js, runtime/js/99_main.js, runtime/runtime.rs, runtime/tests/js/versions_tests.js, runtime/tests/runtime_integration_tests.rs
Add a new Zinnia API exposing runtime and V8 versions to modules.
Related: https://github.com/filecoin-station/spark-api/pull/29
In the future, we can expose this via `import versions from "zinnia:versions"` - see #236.
=> feat: Zinnia.versions.{zinnia,v8}

runtime/tests/js/timers_tests.js
https://github.com/filecoin-station/zinnia/actions/runs/5374177743/jobs/9749361834?pr=264
> Error: Error: setTimeout(50) should take between 40 to 120 ms to execute, but took 208 ms instead
=> fix: relax timer test timeout

Cargo.lock, cli/Cargo.toml, cli/main.rs, daemon/Cargo.toml, daemon/main.rs, runtime/Cargo.toml, runtime/js/99_main.js, runtime/js/fetch.js, runtime/runtime.rs, runtime/tests/helpers/mod.rs, runtime/tests/js/ipfs_retrieval_tests.js
Configure Lassie HTTP server to require authorization with the configured access token.
This change does not affect Zinnia modules with one exception: `fetch('ipfs://`) requests are not allowed to send an `Authorization` header now.
Also upgrade Lassie from v0.4.0 to v0.5.1. Release notes: 
- https://github.com/filecoin-station/rusty-lassie/releases/tag/v0.5.0
- https://github.com/filecoin-station/rusty-lassie/releases/tag/v0.5.1
=> feat: secure Lassie server using authorization

.github/workflows/ci.yaml, .github/workflows/release.yml
rusty-lassie doesn't support Go version 1.21 yet.
See also https://github.com/filecoin-station/rusty-lassie/pull/53
=> ci: use Go version 1.20

Cargo.lock, Cargo.toml, ext/libp2p/lib.rs, runtime/Cargo.toml, runtime/runtime.rs, runtime/tests/fetch_api_tests.rs
- bump `deno_core` to 0.204.0, the version used by other deno crates
- bump other deno crates to version 1.36.3 / 2023.08.24
https://github.com/denoland/deno/releases/tag/v1.36.3
Notably, this fixes builds using recent rust versions (e.g. 1.72.0).
=> deps: upgrade Deno to 1.36.3 / 2023.08.24

Cargo.lock, runtime/Cargo.toml
This also fixes the webpki-related vulnerability for Fetch API.
The vulnerability is still affecting libp2p, though.
=> deps: upgrade Deno to 1.36.4 / 2023.09.01

.cargo/config.toml, Cargo.toml, cli/Cargo.toml, daemon/Cargo.toml, ext/libp2p/Cargo.toml, runtime/Cargo.toml
See https://doc.rust-lang.org/stable/cargo/reference/workspaces.html#the-lints-table
=> chore: move lint config to Cargo.toml

daemon/main.rs, daemon/station_reporter.rs
Add a new activity event to report when the runtime started. We can expose
this new event in the JS API for Station Modules in the future too.
Example output:
```
{"type":"activity:started","module":null}
{"type":"jobs-completed","total":5,"modules":{"main":5}}
```
See https://github.com/filecoin-station/core/pull/327#discussion_r1474361506
=> feat: `activity:started` event

.github/workflows/ci.yaml, .github/workflows/release.yml
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
=> ci: use M1 macOS runner

.github/workflows/release.yml
Rework all `if` conditions in workflow steps from checking the exact string equality (e.g. `matrix.os == 'macos-latest'`) to checking only the platform prefix (e.g. `startsWith(matrix.os,  'macos-')`).
This fixes the regression introduced by eb98870 (#490), see https://github.com/filecoin-station/zinnia/actions/runs/8718338987
=> ci: make release builds agnostic of runner version

daemon/main.rs, daemon/tests/daemon_tests.rs, docs/building-modules.md, runtime/runtime.rs, runtime/tests/js/station_apis_tests.js
An ED25519 public key exported in the SPKI format has always 44 bytes, that is 88 characters in hexadecimal encoding.
This is a follow-up for:
- #529
=> fix: change the hard-coded station id to 88 chars

docs/building-modules.md, runtime/runtime.rs, runtime/tests/js/station_apis_tests.js
Fix Spark Checker CI builds - e.g. here: https://github.com/filecoin-station/spark/actions/runs/9063057104/job/24898210891
See also:
- https://github.com/filecoin-station/spark-api/pull/258
=> fix: use `0x00(...)0DEaD` as the dev wallet

.github/workflows/ci.yaml, .github/workflows/release.yml
Our release binaries are crashing when built by Rust 1.78.
Suspected cause: Rust 1.78 upgraded LLVM from v17 to v18, perhaps our ancient Deno version is not compatible with that.
=> ci: pin Rust version to 1.77

runtime/module_loader.rs
Let's try to get more visibility into the following issue:
- https://github.com/filecoin-station/zinnia/issues/485
=> feat: more info when module is outside of the root

runtime/module_loader.rs, runtime/tests/js/module_loader_tests.js
In 31c029238 (#557), I improved the error message printed when the module is outside of the root dir to include the file path of the imported module. That's not enough to troubleshoot the problem, because we print the non-canonical path, which is potentially different from the string we use to check if the module path is within the root dir.
In this commit, I refactored the method to make the code easier to follow, and improved the error message to print the canonicalized paths of the module and the root dir.
Links:
- https://github.com/filecoin-station/zinnia/issues/485
=> fix: report canonicalized module path

runtime/module_loader.rs
A small UX improvement to simplify troubleshooting.
Links:
- https://github.com/filecoin-station/zinnia/pull/560
- https://github.com/filecoin-station/zinnia/issues/485
=> fix: print module path when cannonicalize fails

daemon/station_reporter.rs
Fixes https://github.com/filecoin-station/core/issues/583 (hopefully).
This change has a side effect when running a high-job-frequency module like the former Saturn L2 node or Voyager:
- Before, we would update the state file every time a job was completed.
- Now, we update the state file at most once per 200ms, as configured via `job_report_delay`:
https://github.com/filecoin-station/zinnia/blob/9d882e48e5b9f0fdab2530fdc08c69987a4237a6/daemon/main.rs#L78-L82
I am arguing this is a change for the better because there is no point in hammering the file system (and SSD drives) with too frequent updates of the state file.
=> fix: report job count only after it was persisted

daemon/tests/daemon_tests.rs, daemon/tests/fixtures/fetch-ipfs-with-delay.js
A bunch of Dependabot PRs are blocked from landing because of this test
failing.
In this PR, I am fixing the test by changing the CID we are downloading.
I am also adding more diagnostics to simplify troubleshooting in the future.
Here is how to run this single test and get the additional info:
```
cargo test --test daemon_tests -- --nocapture
```
=> test: fix "it_removes_lassie_temp_on_start"

.github/workflows/ci.yaml, .github/workflows/release.yml
=> ci: use Rust 1.85 for building release binaries

cross/Dockerfile
Fixes regression introduced by #668 by upgrading golang toolchain version from `v1.20` to `v1.22` as expected by `rusty-lassie`. 
Related to #691 
Partially closes #689
=> fix: Linux builds

cli/README.md
This pull request updates the `cli/README.md` file to specify the required versions of Go and Rust for building the project.
Closes #693
=> docs: Specify rust and go versions in docs

.github/workflows/ci.yaml
I noticed that GitHub is not running the `ci.yaml` workflow for new commits pushed to the `main` branch. In this PR, I am removing the branch restriction from the trigger config.
=> ci: run CI on push to any branch

daemon/tests/fixtures/fetch-ipfs-with-delay.js, runtime/tests/js/ipfs_retrieval_tests.js
IPNI service is often downgraded and our tests fail as a result.
This commit adds `protocol` and `providers` url query parameters to all Lassie requests so that Lassie can skip the provider lookup.
A similar change for rusty-lassie:
- https://github.com/CheckerNetwork/rusty-lassie/pull/164
=> test: avoid IPNI lookups

runtime/tests/js/fetch_tests.js, runtime/tests/js/webapis_tests.js
This is a follow-up for https://github.com/CheckerNetwork/zinnia/pull/717 where we upgraded Deno to the version adding these new APIs.
- `URL.parse()`
- `Float16Array`
- `Response.bytes()`
Parent issue:
- https://github.com/CheckerNetwork/zinnia/issues/676
=> test: add tests for new Web Platform APIs

.prettierignore, runtime/module_loader.rs, runtime/tests/js/typescript_fixtures/typescript_stack_trace.ts, runtime/tests/runtime_integration_tests.rs
This is a follow-up for #717, where we added TypeScript transpilation but did not test how it works in practice.
The implementation is based on this Deno example:
https://github.com/denoland/deno_core/blob/0.343.0/core/examples/ts_module_loader.rs
Example code:
```ts
interface User {
name: string;
email: string;
}
const err: Error = new Error("boom!"); throw err;
```
Deno output:
```
error: Uncaught (in promise) Error: boom!
const err: Error = new Error("boom!"); throw err;
^
at file:///project/x.ts:6:20
```
Zinnia before this change - notice the missing `: Error` snippet and wrong source code line & column numbers:
```
error: Uncaught (in promise) Error: boom!
const err = new Error("boom!");
^
at file:///project/x.ts:1:13
```
Zinnia after this change (same output as from Deno):
``` …
```
=> fix: error stack traces in transpiled TypeScript

.github/workflows/ci.yaml, .github/workflows/release.yml
Upgrade `cross` to the current latest version in git to fix the following build error:
```
= note: /target/x86_64-unknown-linux-gnu/release/deps/libv8-2ad472a53f497811.rlib(wasm-objects.o): In function `v8::internal::WasmMemoryMapDescriptor::NewFromAnonymous(v8::internal::Isolate*, unsigned long)':
./../../../../v8/src/wasm/wasm-objects.cc:1183: undefined reference to `memfd_create'
```
This should fix the failing release builds as seen e.g. here: https://github.com/CheckerNetwork/zinnia/actions/runs/14613159941/job/40995245251
References:
- https://github.com/CheckerNetwork/zinnia/pull/200
- https://github.com/cross-rs/cross/issues/1510
=> ci: fix Linux release builds

docs/building-modules.md
This is a follow-up for https://github.com/CheckerNetwork/zinnia/pull/722 to enable subnet builders to experiment with WebAssembly code and give us feedback on what to improve.
Links:
- https://github.com/CheckerNetwork/zinnia/issues/706
- https://github.com/CheckerNetwork/zinnia/issues/74
=> docs: describe how to use WASM modules

docs/building-modules.md, runtime/js/90_zinnia_apis.js, runtime/js/98_global_scope.js, runtime/tests/js/http_tests.js
This PR adds [createHttpClient](https://docs.deno.com/api/deno/~/Deno.createHttpClient) function to Zinnia namespace. 
Currently we're using a default http client that Deno runtime [creates and reuses for each request](https://github.com/denoland/deno/blob/0f6d515c91a486cc30acd34d1237f7fdaf95df8c/ext/fetch/lib.rs#L526-L531). 
Adding this function to a global runtime would enable us to create a new http client on per request basis and potentially enable proxy rotation for each request.
=> chore: add `createHttpClient` to Zinnia namespace
